cache: pip
dist: trusty
addons:
    apt:
        packages:
            - libxml2-dev

env:
    global:
        - PYTHONHASHSEED=random

matrix:
    include:
        - os: linux
          language: python
          python: 2.7
          env: BUILDER=build.py CC=gcc
        - os: linux
          language: python
          python: 2.7
          env: BUILDER=build.py CC=clang
        - os: linux
          language: python
          python: 2.7
          env: BUILDER=setup.py
        - os: linux
          language: python
          python: 3.4
          env: BUILDER=setup.py

        - os: osx
          python:
          language: generic
          env: BUILDER=setup.py

before_install:
    - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew install libxml2; fi

install:
    - pip install cython
    - git clone --depth 1 https://github.com/lxml/lxml && cd lxml && CFLAGS=-O0 python setup.py install && cd ..
    - python -c "from lxml import etree; print(etree)"

script:
    - python $BUILDER test
