language: python
cache: pip
dist: trusty
addons:
    apt:
        packages:
            - libxml2-dev

python:
    - 2.7
    - 3.4

env:
    global:
        - PYTHONHASHSEED=random
    matrix:
        - BUILDER=build.py CC=gcc
        - BUILDER=build.py CC=clang
        - BUILDER=setup.py

matrix:
    exclude:
        - python: 3.4
          env: BUILDER=build.py CC=gcc
        - python: 3.4
          env: BUILDER=build.py CC=clang

install:
    - pip install cython
    - git clone --depth 1 https://github.com/lxml/lxml && cd lxml && CFLAGS=-O0 python setup.py install && cd ..
    - python -c "from lxml import etree; print(etree)"

script:
    - python $BUILDER test
