cache: pip
dist: trusty
sudo: false
addons:
    apt:
        packages:
            - libxml2-dev

env:
    global:
        - PYTHONHASHSEED=random

matrix:
    include:
        - os: linux
          language: python
          python: 2.7
          env: BUILDER=build.py CC=gcc
        - os: linux
          language: python
          python: 2.7
          env: BUILDER=build.py CC=clang
        - os: linux
          language: python
          python: 2.7
          env: BUILDER=setup.py
        - os: linux
          language: python
          python: 3.4
          env: BUILDER=setup.py

        - os: osx
          python:
          language: generic
          env: BUILDER=setup.py

install:
    - pip install --no-binary lxml chardet lxml
    - python -c "from lxml import etree; print(etree)"

script:
    - python $BUILDER test
